#
# Services configuration
#

# ---------------------------------------
#
# Below is the configuration for the simple web service API.
# See http://docs.collectiveaccess.org/wiki/SimpleAPI
#
# ---------------------------------------
simple_api_endpoints = {
	objectDetail = {
		type = detail,
		table = ca_objects,
		restrictToTypes = [],
		checkAccess = [],
		content = {
			object_id = ^ca_objects.object_id,
			display_label = ^ca_objects.preferred_labels
		}
	},
	
	objectSearch = {
    		type = search,
    		table = ca_objects,
    		content = {
    			object_id = ^ca_objects.object_id,
    			display_label = ^ca_objects.preferred_labels
    			
    		}
  },
  imageSearch = {
    		type = search,
    		table = ca_objects,
    		content = {
    			object_id = ^ca_objects.object_id,
    			image = ^ca_object_representations.media.small
    			
    		}    		
  }
}
# ---------------------------------------
# enable switches for service groups that
# shouldn't be enabled by default
# (deprecated)
# ---------------------------------------

enable_access_control = 0
